import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ReactLenis} from "@/lib/lenis"
import Footer from "./components/Layout/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SEA SMARTZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark" >
      <ReactLenis root>
  
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background `}
      >
        <main className="min-h-screen text-muted-foreground flex flex-col max-w-7xl  mx-auto ">

        {children}
        </main>
        <Footer/>
      </body>
        </ReactLenis>
    </html>
  );
}
